openapi: '3.0.0'
info:
  version: 1.0.0
  title: Holberton Talent Marketplace API
  description: Api for the web application.
paths:
  /holbies:
    get:
      description: |
        Returns all holbies
      operationId: findHolbies
      responses:
        '200':
          description: holbie response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Holbie'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      description: Creates a new holbie.
      operationId: addHolbie
      requestBody:
        description: Holbie to add to the app
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Holbie'
      responses:
        '200':
          description: holbie response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Holbie'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /holbies/{id}:
    get:
      description: Returns a holbie based on id
      operationId: find holbie by id
      parameters:
        - name: id
          in: path
          description: ID holbie to fetch
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Holbie response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Holbie'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      description: deletes a single holbie based on the ID supplied
      operationId: deleteHolbie
      parameters:
        - name: id
          in: path
          description: ID of pet to delete
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: holbie deleted
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      description: Update a holbie based on id
      operationId: find holbie and update
      parameters:
        - name: id
          in: path
          description: ID holbie to fetch
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Holbie response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Holbie'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /companies:
    get:
      description: |
        Returns all companies
      operationId: findcompanies
      responses:
        '200':
          description: company response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Company'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      description: Creates a new company.
      operationId: addCompany
      requestBody:
        description: Company to add to the app
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Company'
      responses:
        '200':
          description: company response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Company'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /companies/{id}:
    get:
      description: Returns a company based on id
      operationId: find company by id
      parameters:
        - name: id
          in: path
          description: ID holbie to fetch
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Holbie response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Company'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      description: deletes a single company based on the ID supplied
      operationId: deleteCompany
      parameters:
        - name: id
          in: path
          description: ID of pet to delete
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: holbie deleted
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      description: Update a company based on id
      operationId: find company and update
      parameters:
        - name: id
          in: path
          description: ID company to fetch
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Holbie response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Company'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Holbie:
      required:
        - name
        - gender
        - about_me
        - technologies
        - linkedin
      properties:
        gender:
          type: string
          example: Male
        name:
          type: string
          example: Juan Camilo Cadavid Velásquez
        about_me:
          type: string
          example: Student at Holberton School
        locaion:
          type: string
          example: Medellín, Colombia
        most_amazing_thing:
          type: string
          example: I reached English fluency at a very early age, becoming the first bilingual person in my family.
        previous_education:
          type: string
          example: No preivous education
        technologies:
          type: string
          example: Python, C, JavaScript, Node.js, MySQL, PostgreSQL
        linkedin:
          type: string
          example: https://www.linkedin.com/in/juan-camilo-cadavid-velásquez-682b94205/
        github:
          type: string
          example: https://github.com/Juansu01
    Company:
      required:
      - name
      - about_us
      - technologies
      properties:
        name:
          type: string
        about_us:
          type: string
        location:
          type: string
        technologies:
          type: string
        contact_link:
          type: string
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
